# This file is not installed -- you need to configure yourself

[rsync-proxy-nonexist]
# Ban 1d if requests nonexist module 10 times in 1h
enabled  = true
port     = rsync
filter   = rsync-proxy-nonexist
logpath  = /var/log/rsync-proxy/access.log
maxretry = 10
findtime = 3600
bantime  = 86400
backend  = pyinotify
chain    = fail2ban
banaction = iptables-ipset-drop[chain="%(chain)s"]
# ignoreip = 127.0.0.1

[rsync-proxy-connection]
# Ban 1d if starts requesting, starts queueing, or hits queue full 15 times in 1m
enabled  = true
port     = rsync
filter   = rsync-proxy-connection
logpath  = /var/log/rsync-proxy/access.log
maxretry = 15
findtime = 60
bantime  = 86400
backend  = pyinotify
chain    = fail2ban
banaction = iptables-ipset-drop[chain="%(chain)s"]
# ignoreip = 127.0.0.1
