/var/log/rsync-proxy/*.log
{
        create 0644 rsync-proxy nogroup
        daily
        rotate 200
        dateext
        compress
        notifempty
        missingok

        postrotate
                systemctl reload rsync-proxy.service
        endscript
}
