/var/log/rsync-proxy/*.log
{
        create 0644 rsync-proxy nogroup
        daily
        rotate 200
        dateext
        compress
        notifempty
        missingok

        postrotate
                /usr/bin/rsync-proxy --config=/etc/rsync-proxy/config.toml reopen-logs
        endscript
}
