name: Go

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: ['*']
    tags: ['*']

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v3
      with:
        go-version: ^1.19
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Install rsync
      run: sudo apt install -y rsync

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
        version: latest

    - name: Get dependencies and run tests
      run: go test -race -v ./...

    - name: Build
      if: startsWith(github.ref, 'refs/tags/')
      run: make -j releases

    - name: Upload Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: rsync-proxy-v*
        draft: false
        prerelease: false
